### ISSUE TITLE
vue-cli3 引入后运行报错 ScriptTimestampWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by ghost** [pingan8787/script-timestamp-webpack-plugin#1]
```html /public/index.html
<!DOCTYPE html>
<html lang="en">
  <body>
    <!--SetScriptTimestampPlugin inset script-->
  </body>
</html>
```
```js vue.config.js
const ScriptTimestampWebpackPlugin = require("script-timestamp-webpack-plugin");
module.exports = {
    configureWebpack:{
        plugins: [
          new ScriptTimestampWebpackPlugin()
        ]
    },
};
```

```bash
npm run serve

 ERROR  Error loading vue.config.js:
 ERROR  SyntaxError: Unexpected identifier
import ScriptTimestampWebpackPlugin from 'script-timestamp-webpack-plugin';
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Service.loadUserOptions (D:\work\monkey\wenbo\wenbo\node_modules\@vue\cli-service\lib\Service.js:316:22)
    at Service.init (D:\work\monkey\wenbo\wenbo\node_modules\@vue\cli-service\lib\Service.js:75:30)
    at Service.run (D:\work\monkey\wenbo\wenbo\node_modules\@vue\cli-service\lib\Service.js:221:10)
```

**Comment by pingan8787** [comment]
@zimluk 感谢你的提醒，已经调整插件入口文件，你重新安装一下即可，最新版本号为1.0.2.
